;this file for FamiTone2 library generated by text2data tool

testmus_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $03
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env2,@env7,@env8
	.byte $00
	.byte $30 ;instrument $05
	.word @env2,@env0,@env8
	.byte $00
	.byte $30 ;instrument $06
	.word @env3,@env7,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $09
	.word @env5,@env0,@env9
	.byte $00
	.byte $70 ;instrument $0a
	.word @env6,@env0,@env10
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cb,$c8,$c6,$c5,$c5,$c4,$c4,$c3,$c3,$c0,$00,$09
@env2:
	.byte $cf,$cc,$c7,$c2,$c0,$00,$04
@env3:
	.byte $cf,$ce,$cd,$cd,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c6,$c5,$c4,$c3,$c3
	.byte $c2,$c0,$00,$11
@env4:
	.byte $c8,$c9,$02,$ca,$03,$cb,$cb,$ca,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$02
	.byte $c0,$00,$10
@env5:
	.byte $cf,$0d,$ce,$06,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$c8
	.byte $c7,$c7,$c6,$c5,$c5,$c4,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$00,$1c
@env6:
	.byte $cf,$ce,$03,$cd,$cd,$cc,$cc,$cb,$cb,$ca,$ca,$c9,$c9,$c8,$02,$c7
	.byte $c6,$c6,$c5,$c5,$c4,$c4,$c3,$00,$16
@env7:
	.byte $c0,$c1,$c2,$c3,$00,$03
@env8:
	.byte $bf,$00,$00
@env9:
	.byte $c0,$05,$c1,$02,$c2,$02,$c3,$c5,$c8,$cf,$db,$00,$0a
@env10:
	.byte $c0,$12,$c6,$cc,$cc,$c6,$c0,$ba,$b4,$b4,$ba,$c0,$00,$02


@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$1e,$36,$2c,$1e,$36,$2c,$3a,$36,$3e,$3a,$40,$3e,$3e,$40,$36
	.byte $3e,$1e,$36,$2c,$1e,$36,$2c,$3a,$36,$3e,$3a,$40,$3e,$3e,$40,$36
	.byte $3e
@ref1:
	.byte $1e,$36,$2c,$1e,$36,$2c,$3a,$36,$3e,$3a,$40,$3e,$3e,$40,$36,$3e
	.byte $1e,$36,$2c,$1e,$36,$2c,$3a,$36,$3e,$3a,$40,$3e,$3e,$40,$36,$3e
	.byte $ff,$20
	.word @ref1
	.byte $ff,$20
	.word @ref1
@ref4:
	.byte $8a,$66,$85,$66,$85,$66,$85,$66,$87,$8c,$3a,$91,$01,$3f,$40
@ref5:
	.byte $81,$36,$91,$01,$3b,$3d,$36,$89,$01,$32,$89,$00
@ref6:
	.byte $8a,$66,$85,$66,$85,$66,$85,$66,$87,$8c,$52,$89,$4e,$85,$37,$3b
	.byte $3c
@ref7:
	.byte $81,$41,$44,$8d,$37,$3d,$45,$40,$87,$2e,$89,$32,$83,$3a
	.byte $ff,$20
	.word @ref0
	.byte $ff,$20
	.word @ref1
@ref10:
	.byte $88,$2c,$36,$3e,$2c,$36,$3e,$2c,$36,$3e,$2c,$36,$3e,$2c,$36,$3e
	.byte $2c,$28,$32,$3a,$28,$32,$3a,$28,$32,$3a,$28,$32,$3a,$28,$32,$3a
	.byte $28
@ref11:
	.byte $24,$2e,$36,$24,$2e,$36,$24,$2e,$36,$24,$2e,$36,$24,$2e,$36,$24
	.byte $28,$32,$3a,$28,$32,$3a,$28,$32,$3a,$28,$32,$3a,$28,$32,$3a,$28
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref12:
	.byte $80,$4e,$66,$5c,$4e,$66,$5c,$6a,$66,$6e,$6a,$70,$6e,$6e,$70,$66
	.byte $6e,$4e,$66,$5c,$4e,$66,$5c,$6a,$66,$6e,$6a,$70,$6e,$6e,$70,$66
	.byte $6e
@ref13:
	.byte $4e,$66,$5c,$4e,$66,$5c,$6a,$66,$6e,$6a,$70,$6e,$6e,$70,$66,$6e
	.byte $4e,$66,$5c,$4e,$66,$5c,$6a,$66,$6e,$6a,$70,$6e,$6e,$70,$66,$6e
	.byte $ff,$20
	.word @ref13
	.byte $ff,$20
	.word @ref13
@ref16:
	.byte $00,$85,$8c,$36,$00,$3a,$36,$3e,$3a,$40,$3e,$44,$40,$3a,$91,$01
	.byte $3f,$41,$36,$81
@ref17:
	.byte $8f,$01,$3b,$3d,$36,$89,$01,$32,$89,$00,$85
@ref18:
	.byte $00,$85,$36,$00,$3a,$36,$3e,$3a,$40,$3e,$44,$40,$52,$89,$4e,$85
	.byte $37,$3b,$3d,$40,$81
@ref19:
	.byte $44,$8d,$37,$3d,$45,$40,$8d,$3c,$89,$3a,$85
@ref20:
	.byte $00,$85,$36,$00,$3a,$36,$3e,$3a,$40,$3e,$44,$40,$3a,$91,$01,$3f
	.byte $41,$36,$81
	.byte $ff,$0b
	.word @ref17
	.byte $ff,$15
	.word @ref18
	.byte $ff,$0b
	.word @ref19
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref24:
	.byte $80,$1f,$37,$1f,$37,$1f,$37,$1f,$37,$1b,$33,$1b,$33,$1b,$33,$1b
	.byte $32,$81
@ref25:
	.byte $17,$2f,$17,$2f,$17,$2f,$17,$2f,$1b,$33,$1b,$33,$1b,$33,$1b,$32
	.byte $81
@ref26:
	.byte $1f,$37,$1f,$37,$1f,$37,$1f,$37,$1b,$33,$1b,$33,$1b,$33,$1b,$32
	.byte $81
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref26
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref26
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref26
	.byte $ff,$11
	.word @ref25
	.byte $ff,$11
	.word @ref26
	.byte $ff,$11
	.word @ref25
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref36:
	.byte $84,$09,$82,$18,$1c,$86,$07,$82,$18,$1c,$84,$09,$82,$18,$1c,$86
	.byte $07,$82,$18,$1c,$84,$09,$82,$18,$1c,$86,$07,$82,$18,$84,$08,$09
	.byte $82,$18,$1c,$86,$07,$06,$06
@ref37:
	.byte $84,$09,$82,$18,$1c,$86,$07,$82,$18,$1c,$84,$09,$86,$06,$82,$1c
	.byte $86,$07,$82,$18,$1c,$84,$09,$82,$18,$1c,$86,$07,$82,$18,$1c,$84
	.byte $08,$86,$06,$06,$82,$1c,$84,$08,$86,$06,$82,$18,$86,$06
	.byte $ff,$18
	.word @ref36
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$18
	.word @ref36
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$18
	.word @ref36
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$18
	.word @ref36
	.byte $ff,$1a
	.word @ref37
	.byte $ff,$18
	.word @ref36
	.byte $ff,$1a
	.word @ref37
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref48:
	.byte $00,$bd
@ref49:
	.byte $bf
@ref50:
	.byte $00,$bd
@ref51:
	.byte $bf
@ref52:
	.byte $00,$bd
@ref53:
	.byte $bf
@ref54:
	.byte $00,$bd
@ref55:
	.byte $bf
@ref56:
	.byte $00,$bd
@ref57:
	.byte $bf
@ref58:
	.byte $00,$bd
@ref59:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
